add max_tree_cover to get_data()
wri/cities-cif pull request #46
Opened 2024-06-07 20:12 UTC by tedw0ng

## Did you read the Contributor Guide?

- Yes, I have read [How to contribute](https://github.com/wri/cities-cif#How-to-contribute)

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://gfw.atlassian.net/browse/CIF-XXX. The PR name follows the format `[CIF-XXX] my subject`.

- No, this is a documentation update. The PR name follows the format `[DOCS] my subject`.

## What changes were proposed in this PR?

## How was this patch tested?

## Did this PR include necessary documentation updates?

- Yes, I am adding a new API feature.
- Yes, I have updated the documentation update.
- No, this PR does not affect any public API so no need to change the docs.

2024-06-11 12:49 UTC, weiqi-tori requested changes

2024-06-11 12:49 UTC, weiqi-tori commented on city_metrix/layers/tree_cover.py
>          self.min_tree_cover = min_tree_cover
`self.max_tree_cover = max_tree_cover`

2024-06-11 15:34 UTC, tedw0ng commented on city_metrix/layers/tree_cover.py
>          self.min_tree_cover = min_tree_cover
Added that line.

2024-06-12 20:38 UTC, jterry64 approved these changes

2024-06-14 08:03 UTC, weiqi-tori approved these changes

2024-06-14 08:04 UTC, merged