Bugfix/pytest
wri/cities-cif pull request #50
Opened 2024-06-26 14:09 UTC by chrowe

## Did you read the Contributor Guide?

- Yes, I have read [How to contribute](https://github.com/wri/cities-cif#How-to-contribute)

- No, I haven't read it.

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://gfw.atlassian.net/browse/CIF-XXX. The PR name follows the format `[CIF-XXX] my subject`.

- No, this is a documentation update. The PR name follows the format `[DOCS] my subject`.

## What changes were proposed in this PR?

## How was this patch tested?

## Did this PR include necessary documentation updates?

- Yes, I am adding a new API feature.
- Yes, I have updated the documentation update.
- No, this PR does not affect any public API so no need to change the docs.

2024-07-11 13:10 UTC, chrowe commented
@jterry64 Arsh is running into issue getting the the GH Actions Repository secrets to work.

2024-07-16 16:41 UTC, chrowe commented on .github/workflows/tests.yml
I think we can just delete this

2024-07-29 22:37 UTC, jterry64 approved these changes

2024-07-29 22:46 UTC, jterry64 requested changes

2024-07-29 22:46 UTC, jterry64 commented on .github/workflows/tests.yml
yeah @arshdoda can you delete this?

2024-07-29 22:46 UTC, jterry64 commented on .github/workflows/dev_ci_cd.yml
> +    - name: Install Packages
Have you tried using this to set up the conda environment.yml file instead of having a different requirements.txt?

2024-07-30 13:46 UTC, chrowe commented
@arshdoda can you try using the setup.py for this? Now that Tori got that working in Colab https://github.com/wri/cities-cif/pull/54 I think it should work here too.

2024-07-30 15:26 UTC, chrowe commented
Actually, lets just merge this and I will create a new issue to look into using setup.py

@arshdoda can you just resolve the merge conflicts?

2024-07-31 15:18 UTC, chrowe reviewed
Just one change requested

2024-07-31 15:18 UTC, chrowe commented on environment.yml
> +      - cartoframes==1.2.5
We actually want to remove cartoframes for now

2024-07-31 15:57 UTC, merged