Use pytest to dump layers to geotiff files
wri/cities-cif pull request #61
Opened 2024-08-14 03:22 UTC by kcartier-wri

## Is this PR related to a JIRA ticket?
https://gfw.atlassian.net/browse/CIF-247

## What changes were proposed in this PR?
Extend testing

## How was this patch tested?
locally

2024-08-14 04:22 UTC, kcartier-wri commented
Justin - As I mentioned, I'd like to include a way of dumping layers to geotiff files along with a QGIS project file for viewing them. What do you think of this current approach. I'm not fully satisfied with it, so am interested in your suggestions. Thanks.

2024-08-23 16:14 UTC, chrowe requested changes

2024-08-23 16:14 UTC, chrowe commented on tests/resources/layer_dumps_for_br_lauro_de_freitas/test_write_layers_to_geotiff.py
I get
```
FAILED tests/resources/layer_dumps_for_br_lauro_de_freitas/test_write_layers_to_geotiff.py::test_geotiff_writing - UnboundLocalError: local variable 'overture_buildings' referenced before assignment
```
When running 
`pytest tests/resources/layer_dumps_for_br_lauro_de_freitas/test_write_layers_to_geotiff.py`

2024-08-23 17:12 UTC, kcartier-wri commented on tools/general_tools.py
> +        raise ValueError('Method not implemented for this OS.')
create_temp_folder function now uses tempfile library, so MacOS should now be handled. Please test or your machine.

2024-08-23 17:35 UTC, kcartier-wri commented on city_metrix/layers/land_surface_temperature.py
> +    #     self.data.rio.to_raster(output_path)
done

2024-08-23 17:35 UTC, kcartier-wri commented on city_metrix/layers/high_land_surface_temperature.py
> +    #     self.data.rio.to_raster(output_path)
done

2024-08-23 17:37 UTC, kcartier-wri commented on tests/resources/layer_dumps_for_br_lauro_de_freitas/test_write_layers_to_geotiff.py
I haven't been able to reproduce this issue and haven't even spotted the overture_buildings variable in the code. Also, the automatic execution in github passes without issue.

Could you isolate it further?

2024-08-23 18:05 UTC, jterry64 approved these changes
Looks good to me!

2024-08-23 20:00 UTC, chrowe commented on tests/resources/layer_dumps_for_br_lauro_de_freitas/test_write_layers_to_geotiff.py
I was able to run it with the latest changes

2024-08-23 20:03 UTC, chrowe approved these changes

2024-08-23 20:37 UTC, kcartier-wri commented on city_metrix/layers/high_land_surface_temperature.py
> +    #     self.data.rio.to_raster(output_path)
done

2024-08-23 20:39 UTC, merged