Cif 234 veg water change
wri/cities-cif pull request #91
Opened 2024-11-11 06:14 UTC by weiqi-tori

https://gfw.atlassian.net/browse/CIF-234

TODO: layer generation and zonal stats use different spatial resolutions

2024-12-05 22:06 UTC, tedw0ng requested changes
Instead of returning (gain_pixels - loss_pixels) / start_pixels, can we return gain_area and loss_area, or (gain_area - loss_area)? I'm concerned that ratios are hard to use, but a user could calculate a ratio if desired if they could also get start_area.

2024-12-06 09:56 UTC, weiqi-tori commented
> Instead of returning (gain_pixels - loss_pixels) / start_pixels, can we return gain_area and loss_area, or (gain_area - loss_area)? I'm concerned that ratios are hard to use, but a user could calculate a ratio if desired if they could also get start_area.

We could update the script to do that. Do we want it to be one indicator script with different options of output? Or multiple indicators using the same layer? We don't currently have indicator(s) like this in CIF. @chrowe @S-AI-F

2024-12-06 11:16 UTC, S-AI-F commented
Agree with @tedw0ng  that the only ratio is hard to use as output. Since we don't have other metrics with multiple outputs and to keep the structure simple for now, @weiqi-tori  i propose to develop them as sperate functions in the same metric script with one output by function (same logic as glad_lulc layer):

- vegetation_water_change_gain_areas
- vegetation_water_change_loss_areas
- vegetation_water_change_gain_loss_ratio

What do you think @tedw0ng  @weiqi-tori ?

2024-12-06 15:09 UTC, tedw0ng commented
Yes this would be fine. The non-ratio names should be *_area, not *_areas.

2025-01-11 21:13 UTC, tedw0ng approved these changes

2025-01-13 02:52 UTC, merged